// SPDX-License-Identifier: BUSL-1.1

export const Images = {
  tabbar: {
    itemBackground: require('./tabbar/item-background.png'),
    miningBackground: require('./tabbar/mining-background.png'),
  },
  roles: {
    ambassador: require('./roles/ambassador.png'),
    pioneer: require('./roles/pioneer.png'),
    pioneerInactive: require('./roles/pioneer-inactive.png'),
  },
  badges: {
    social0_achieved_true: require('./badges/ice-breaker-active.png'),
    social1_achieved_true: require('./badges/ice-breaker-active.png'),
    social2_achieved_true: require('./badges/ice-breaker-active.png'),
    social3_achieved_true: require('./badges/ice-breaker-active.png'),
    social4_achieved_true: require('./badges/ice-breaker-active.png'),
    social5_achieved_true: require('./badges/ice-breaker-active.png'),
    social6_achieved_true: require('./badges/ice-breaker-active.png'),
    social7_achieved_true: require('./badges/ice-breaker-active.png'),
    social8_achieved_true: require('./badges/ice-breaker-active.png'),
    social9_achieved_true: require('./badges/ice-breaker-active.png'),
    social0_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social1_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social2_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social3_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social4_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social5_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social6_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social7_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social8_achieved_false: require('./badges/cool-breeze-inactive.png'),
    social9_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin0_achieved_true: require('./badges/ice-breaker-active.png'),
    coin1_achieved_true: require('./badges/ice-breaker-active.png'),
    coin2_achieved_true: require('./badges/ice-breaker-active.png'),
    coin3_achieved_true: require('./badges/ice-breaker-active.png'),
    coin4_achieved_true: require('./badges/ice-breaker-active.png'),
    coin5_achieved_true: require('./badges/ice-breaker-active.png'),
    coin6_achieved_true: require('./badges/ice-breaker-active.png'),
    coin7_achieved_true: require('./badges/ice-breaker-active.png'),
    coin8_achieved_true: require('./badges/ice-breaker-active.png'),
    coin9_achieved_true: require('./badges/ice-breaker-active.png'),
    coin0_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin1_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin2_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin3_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin4_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin5_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin6_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin7_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin8_achieved_false: require('./badges/cool-breeze-inactive.png'),
    coin9_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level0_achieved_true: require('./badges/ice-breaker-active.png'),
    level1_achieved_true: require('./badges/ice-breaker-active.png'),
    level2_achieved_true: require('./badges/ice-breaker-active.png'),
    level3_achieved_true: require('./badges/ice-breaker-active.png'),
    level4_achieved_true: require('./badges/ice-breaker-active.png'),
    level5_achieved_true: require('./badges/ice-breaker-active.png'),
    level6_achieved_true: require('./badges/ice-breaker-active.png'),
    level7_achieved_true: require('./badges/ice-breaker-active.png'),
    level8_achieved_true: require('./badges/ice-breaker-active.png'),
    level9_achieved_true: require('./badges/ice-breaker-active.png'),
    level0_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level1_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level2_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level3_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level4_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level5_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level6_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level7_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level8_achieved_false: require('./badges/cool-breeze-inactive.png'),
    level9_achieved_false: require('./badges/cool-breeze-inactive.png'),
    iceBreaker: {
      active: require('./badges/ice-breaker-active.png'),
      inactive: require('./badges/cool-breeze-inactive.png'),
    },
    troubleMaker: {
      active: require('./badges/trouble-maker-active.png'),
    },
    snowyPlow: {
      active: require('./badges/snowy-plow-active.png'),
    },
    frozenMax: {
      active: require('./badges/frozen-max-active.png'),
    },
    coolBreeze: {
      inactive: require('./badges/cool-breeze-inactive.png'),
    },
    bigContender: {
      inactive: require('./badges/big-contender-inactive.png'),
    },
    mastermind: {
      inactive: require('./badges/mastermind-inactive.png'),
      active: require('./badges/mastermind-active.png'),
    },
  },
  phone: {
    confirmPhoneNumber: require('./phone/confirmPhoneNumber.png'),
    modifyPhoneNumber: require('./phone/modifyPhoneNumber.png'),
  },
  backgrounds: {
    linesBg: require('./backgrounds/linesBg.png'),
    privacyBgTop: require('./backgrounds/privacyBgTop.png'),
    privacyBgMiddle: require('./backgrounds/privacyBgMiddle.png'),
    privacyBgBottom: require('./backgrounds/privacyBgBottom.png'),
    linesHeaderBg: require('./backgrounds/linesHeaderBg.png'),
    adoptionCardBg: require('./backgrounds/adoptionCardBg.png'),
    levelCardBg: require('./backgrounds/levelCardBg.png'),
    referralsCardBg: require('./backgrounds/referralsCardBg.png'),
  },
  popUp: {
    updateRequired: require('./popup/please_update.png'),
    error: require('./popup/oops.png'),
    upToDate: require('./popup/already_updated.png'),
    resurrection: require('./popup/resurrection.png'),
  },
} as const;
