// SPDX-License-Identifier: BUSL-1.1

// eslint-disable-next-line no-restricted-imports
import config from 'react-native-config';

export const ENV = {
  BASE_READ_API_URL: config.BASE_READ_API_URL,
  BASE_WRITE_API_URL: config.BASE_WRITE_API_URL,
  MAGIC_LINK_KEY: config.MAGIC_LINK_KEY,
  MAGIC_DEEPLINK_SCHEME: config.MAGIC_DEEPLINK_SCHEME,
  SENTRY_KEY: config.SENTRY_KEY,
  REQUIRE_REFERRAL_REGISTRATION_STEP:
    config.REQUIRE_REFERRAL_REGISTRATION_STEP === 'true',
  GETSTREAM_API_KEY: config.GETSTREAM_API_KEY,
  GETSTREAM_APP_ID: config.GETSTREAM_APP_ID,
  GETSTREAM_TOKEN: config.GETSTREAM_TOKEN,
  GETSTREAM_NOTIFICATIONS_USER_TOKEN: config.GETSTREAM_NOTIFICATIONS_USER_TOKEN,
  GETSTREAM_ANNOUNCEMENTS_USER_TOKEN: config.GETSTREAM_ANNOUNCEMENTS_USER_TOKEN,
  DEEPLINKING_PREFIX: config.DEEPLINKING_PREFIX,
};
